-- 01_creacion_datamart.sql
-- Proyecto BDII - Supermercado Nova

-- STAGING
CREATE TABLE STG_PRODUCTOS (
    id_producto    VARCHAR2(10),
    producto       VARCHAR2(100),
    categoria      VARCHAR2(50),
    precio_base    NUMBER(10,2)
);

CREATE TABLE STG_VENTAS (
    id_venta        VARCHAR2(20),
    fecha            VARCHAR2(20),
    id_producto      VARCHAR2(10),
    cantidad         VARCHAR2(20),
    precio_unitario  VARCHAR2(20),
    sucursal         VARCHAR2(100),
    metodo_pago      VARCHAR2(100)
);

-- DIMENSIONES
CREATE TABLE DIM_TIEMPO (
    id_tiempo     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha         DATE UNIQUE NOT NULL,
    dia           NUMBER(2),
    mes           NUMBER(2),
    nombre_mes    VARCHAR2(20),
    trimestre     VARCHAR2(2),
    anio          NUMBER(4)
);

CREATE TABLE DIM_PRODUCTO (
    id_producto_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_producto VARCHAR2(10) UNIQUE NOT NULL,
    producto       VARCHAR2(100) NOT NULL,
    categoria      VARCHAR2(50),
    precio_base    NUMBER(10,2)
);

CREATE TABLE DIM_SUCURSAL (
    id_sucursal   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal      VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE DIM_METODO_PAGO (
    id_metodo_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metodo_pago    VARCHAR2(100) UNIQUE NOT NULL
);

-- HECHOS
CREATE TABLE FACT_VENTAS (
    id_fact          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta         VARCHAR2(20) NOT NULL,
    id_tiempo        NUMBER NOT NULL,
    id_producto_sk   NUMBER NOT NULL,
    id_sucursal      NUMBER NOT NULL,
    id_metodo_pago   NUMBER NOT NULL,
    cantidad         NUMBER(10) NOT NULL,
    precio_unitario  NUMBER(10,2) NOT NULL,
    monto_venta      NUMBER(12,2) NOT NULL,
    CONSTRAINT fk_fact_tiempo FOREIGN KEY (id_tiempo) REFERENCES DIM_TIEMPO(id_tiempo),
    CONSTRAINT fk_fact_producto FOREIGN KEY (id_producto_sk) REFERENCES DIM_PRODUCTO(id_producto_sk),
    CONSTRAINT fk_fact_sucursal FOREIGN KEY (id_sucursal) REFERENCES DIM_SUCURSAL(id_sucursal),
    CONSTRAINT fk_fact_pago FOREIGN KEY (id_metodo_pago) REFERENCES DIM_METODO_PAGO(id_metodo_pago)
);
